import { ENGINE_STARTERS } from "@/data/engineStarters";
import { linesOrTbd } from "@/lib/helpers";

export function renderFullMarkdown(data) {
  const starter = ENGINE_STARTERS[data.meta.genre];

  return [
    `# ${data.meta.projectName || "Untitled Game Project"} — Full Game Design Document`,
    "",
    `## Project Metadata`,
    `- **Version:** ${linesOrTbd(data.meta.version)}`,
    `- **Genre:** ${starter.label}`,
    `- **Platform:** ${linesOrTbd(data.meta.platform)}`,
    `- **Perspective:** ${linesOrTbd(data.meta.cameraPerspective)}`,
    `- **Visual Style:** ${linesOrTbd(data.meta.visualStyle)}`,
    `- **Target Audience:** ${linesOrTbd(data.meta.audience)}`,
    `- **Scope Target:** ${linesOrTbd(data.concept.scopeTarget)}`,
    `- **Session Length:** ${linesOrTbd(data.concept.sessionLength)}`,
    `- **Monetization:** ${linesOrTbd(data.concept.monetization)}`,
    "",
    `## Concept & Vision`,
    `### Elevator Pitch`,
    linesOrTbd(data.meta.elevatorPitch),
    "",
    `### Concept Summary`,
    linesOrTbd(data.meta.conceptSummary),
    "",
    `### Player Fantasy`,
    linesOrTbd(data.meta.playerFantasy),
    "",
    `### Design Pillars`,
    linesOrTbd(data.concept.pillars),
    "",
    `### Inspirations / Comparables`,
    linesOrTbd(data.concept.inspirations),
    "",
    `### Differentiators`,
    linesOrTbd(data.concept.differentiators),
    "",
    `### Emotional Goal`,
    linesOrTbd(data.concept.emotionalGoal),
    "",
    `### Win / Fail Structure`,
    `- **Win:** ${linesOrTbd(data.concept.winCondition)}`,
    `- **Fail / Loop:** ${linesOrTbd(data.concept.failState)}`,
    "",
    `## World & Narrative`,
    `- **Setting:** ${linesOrTbd(data.world.setting)}`,
    `- **Premise:** ${linesOrTbd(data.world.premise)}`,
    `- **Tone:** ${linesOrTbd(data.world.tone)}`,
    `- **Narrative Structure:** ${linesOrTbd(data.world.narrativeStructure)}`,
    `- **Protagonist:** ${linesOrTbd(data.world.protagonist)}`,
    `- **Antagonist / Opposition:** ${linesOrTbd(data.world.antagonist)}`,
    `- **Factions:** ${linesOrTbd(data.world.factions)}`,
    `- **Lore Summary:** ${linesOrTbd(data.world.loreSummary)}`,
    "",
    `## Core Systems`,
    `- **Core Loop:** ${linesOrTbd(data.systems.coreLoop)}`,
    `- **Progression:** ${linesOrTbd(data.systems.progression)}`,
    `- **Systems List:** ${linesOrTbd(data.systems.systemsList)}`,
    `- **Controls / Input:** ${linesOrTbd(data.systems.controls)}`,
    `- **Combat / Interaction:** ${linesOrTbd(data.systems.combatOrInteraction)}`,
    `- **Economy / Resource Model:** ${linesOrTbd(data.systems.economy)}`,
    `- **Difficulty:** ${linesOrTbd(data.systems.difficulty)}`,
    `- **Save Model:** ${linesOrTbd(data.systems.saveModel)}`,
    `- **Replayability Hooks:** ${linesOrTbd(data.systems.replayability)}`,
    "",
    `## Content Structure`,
    `- **Game Modes:** ${linesOrTbd(data.content.gameModes)}`,
    `- **Level / World Structure:** ${linesOrTbd(data.content.levelsOrWorldStructure)}`,
    `- **Quest / Objective Structure:** ${linesOrTbd(data.content.questStructure)}`,
    `- **Enemies / Challenges:** ${linesOrTbd(data.content.enemiesOrChallenges)}`,
    `- **Items / Abilities / Tools:** ${linesOrTbd(data.content.itemsAbilities)}`,
    `- **UI/UX Notes:** ${linesOrTbd(data.content.uiUxNotes)}`,
    `- **Accessibility:** ${linesOrTbd(data.content.accessibility)}`,
    `- **Onboarding:** ${linesOrTbd(data.content.tutorialOnboarding)}`,
    "",
    `## Asset Pack Requirements`,
    `- **Art:** ${linesOrTbd(data.assets.artNeeds)}`,
    `- **Animation:** ${linesOrTbd(data.assets.animationNeeds)}`,
    `- **Audio:** ${linesOrTbd(data.assets.audioNeeds)}`,
    `- **VFX:** ${linesOrTbd(data.assets.vfxNeeds)}`,
    `- **Narrative Assets:** ${linesOrTbd(data.assets.narrativeAssets)}`,
    `- **Technical Assets:** ${linesOrTbd(data.assets.technicalAssets)}`,
    `- **Asset Strategy:** ${linesOrTbd(data.assets.assetPackApproach)}`,
    "",
    `## Starter Engine Blueprint`,
    `- **Starter Engine Pattern:** ${starter.label}`,
    `- **Suggested Core Loops:** ${starter.coreLoops.join(", ")}`,
    `- **Reusable Modules:** ${starter.engineFit.join(", ")}`,
    `- **Target Engine:** ${linesOrTbd(data.technical.targetEngine)}`,
    `- **Architecture:** ${linesOrTbd(data.technical.engineArchitecture)}`,
    `- **Core Modules:** ${linesOrTbd(data.technical.coreModules)}`,
    `- **AI Partner Tasks:** ${linesOrTbd(data.technical.aiPartnerTasks)}`,
    `- **Required Tools / Pipeline:** ${linesOrTbd(data.technical.requiredTools)}`,
    `- **Performance Targets:** ${linesOrTbd(data.technical.performanceTargets)}`,
    `- **Save Data Requirements:** ${linesOrTbd(data.technical.saveDataRequirements)}`,
    `- **Multiplayer:** ${linesOrTbd(data.technical.multiplayer)}`,
    `- **Live Ops:** ${linesOrTbd(data.technical.liveOps)}`,
    "",
    `## Output Configuration`,
    `- **Tone:** ${linesOrTbd(data.outputStudio.tone)}`,
    `- **Detail Level:** ${linesOrTbd(data.outputStudio.detailLevel)}`,
    `- **Preferred Format:** ${linesOrTbd(data.outputStudio.preferredFormat)}`,
    `- **AI Partner:** ${linesOrTbd(data.outputStudio.aiPartner)}`,
    `- **Coding Style:** ${linesOrTbd(data.outputStudio.codingStyle)}`,
    `- **Additional Instructions:** ${linesOrTbd(data.outputStudio.additionalInstructions)}`,
    "",
    `## AI Partner Build Prompt`,
    `Act as a game design and implementation partner. Use this GDD to: (1) identify missing details, (2) expand lore and content needs, (3) define a reusable asset pack structure, (4) produce a technical implementation roadmap, and (5) scaffold a starter engine for a ${starter.label} using ${linesOrTbd(data.technical.targetEngine)}. Favor modular architecture, reusable systems, data-driven content, placeholder assets where needed, and iterative delivery suitable for AI-assisted development.`,
  ].join("\n");
}
