export const BUILDER_ACTIONS = {
  LOAD_SAVED_DATA: "LOAD_SAVED_DATA",
  SET_FIELD: "SET_FIELD",
  SET_ACTIVE_TAB: "SET_ACTIVE_TAB",
  SAVE_SUCCESS: "SAVE_SUCCESS",
  RESET_ALL: "RESET_ALL",
  APPLY_GENRE_SUGGESTIONS: "APPLY_GENRE_SUGGESTIONS",
  LOAD_TEMPLATE: "LOAD_TEMPLATE",
  COPY_SUCCESS: "COPY_SUCCESS",
  CLEAR_COPIED: "CLEAR_COPIED",
  SYNC_ENGINE_STARTER: "SYNC_ENGINE_STARTER",
};
